version: "3.7"
services:
  postgres:
    image: postgres:12
    container_name: express-ts-ddd-postgres
    environment:
      # allow anyone to connect - even without a password
      # only use for running locally or in CI/CD
      POSTGRES_HOST_AUTH_METHOD: trust
      # create a role with name
      POSTGRES_USER: devel
      # create database test-node-with-docker
      POSTGRES_DB: express-ts-ddd
    # postgres image per default runs on port 5432
    # we need to expose the container to the host machine so we can run our tests
    # if you also run Postgres locally, change the docker host port to something else
    # and update your index.js file inside the config folder
    ports:
      - "2345:5432"
    volumes:
      # docker will run SQL files that are copied to /docker-entrypoint-initdb.d automatically
      # this gives us an easy way to run migrations / create db tables
      # the order in which they are run is determined by the prefix
      # so always prefix your migration files with 01_, 02_, etc
      - ./etc/postgresql/seed:/docker-entrypoint-initdb.d

  pgadmin4:
    image: dpage/pgadmin4
    container_name: express-ts-ddd-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin1234
    ports:
      - "8000:80"
    depends_on:
      - postgres

  app:
    container_name: express-ts-ddd
    build: .
    ports:
      - "8080:8080"
    environment:
      # you need to use the container name as the db host
      # when running in docker-compose. If you use localhost, the container
      # would try to connect to itself
      # https://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockers
      APP_NAME: "express-ts-ddd"
      DATABASE_URL: "postgresql://devel:@postgres:5432/express-ts-ddd?schema=public"
      # this needs to be the container port on which the db runs (the right most number under ports in the postgres service)
      # i.e. we need to specify container port and not the host port
      DB_PORT: 5432
    depends_on:
      - postgres
