name: ci
on:
    pull_request:
    push:
        branches:
            - "master"
jobs:
    test:
        name: Express-TS (Node ${{ matrix.node-version }} on ${{ matrix.operating-system }})
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                node-version: [14.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install -g yarn
            - name: Install dependencies with Yarn
              run: yarn install
            - name: Generate Prisma Client
              run: yarn prisma generate
            - name: Build/Transpile TypeScript files to dist
              run: yarn build
            - name: Run tests
              run: yarn coverage
              env:
                  COGNITO_USER_POOL: ${{ secrets.COGNITO_USER_POOL }}
                  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
                  COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
            - name: Upload coverage result to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./coverage/clover.xml
                  flags: tests
                  name: codecov-umbrella
                  fail_ci_if_error: true
